<a href="https://colab.research.google.com/github/Samsul2121/221230021-Pengantar-ML/blob/main/week-02/latihan_praktikum_4_numpy_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return X @ W + b   # @ = torch.matmul

output = linear_layer(X, weights, bias)

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.maximum(torch.zeros_like(tensor), tensor)

activated = relu_activation(output)

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, eps=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)      # rata-rata per fitur
    std = tensor.std(dim=0, unbiased=False, keepdim=True)  # std per fitur
    return (tensor - mean) / (std + eps)

normalized = simple_batch_norm(X)

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

# Print output
print("✅ Linear layer output (first 5 rows):\n", output[:5])
print("\n✅ ReLU activated output (first 5 rows):\n", activated[:5])
print("\n✅ Batch normalized X (first 5 rows):\n", normalized[:5])
print("\n✅ One-hot encoded labels:\n", one_hot)

# Manual Matrix Multiplication
def manual_matrix_multiply(A, B):
    m, n = A.shape
    n2, p = B.shape
    assert n == n2, "Ukuran matriks tidak cocok!"

    result = torch.zeros((m, p), dtype=A.dtype)
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test matrix multiplication
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("\n✅ Manual matrix multiplication result:\n", manual_result)
print("\n✅ Torch.matmul result:\n", torch_result)

# === Validasi ===
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"

print("✅ Semua operasi PyTorch berhasil dijalankan")


✅ Linear layer output (first 5 rows):
 tensor([[-0.6586],
        [-0.6395],
        [-3.1166],
        [ 5.2388],
        [ 2.3427]])

✅ ReLU activated output (first 5 rows):
 tensor([[0.0000],
        [0.0000],
        [0.0000],
        [5.2388],
        [2.3427]])

✅ Batch normalized X (first 5 rows):
 tensor([[ 0.9841,  0.3946, -0.0593, -1.4373, -1.1074,  0.5776,  0.4093,  1.5303,
          1.8835, -0.5558],
        [ 0.4258, -0.1318,  1.6842, -1.2589,  0.5230,  0.9333, -0.1635, -0.0384,
         -0.4537,  0.0733],
        [ 0.5154,  0.2447, -0.2762, -0.5919, -0.7922,  0.6376,  0.5157,  1.5501,
          0.3260,  0.2496],
        [-1.8520,  0.6044,  0.8322,  1.2920,  0.7516, -0.4509, -2.2780, -0.0686,
         -0.0928,  0.7038],
        [-1.1055,  1.1893, -1.5686, -0.0993,  0.1633, -0.3557, -1.9827,  0.2297,
          0.5026,  0.6032]])

✅ One-hot encoded labels:
 tensor([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [